# Generated by Django 4.1.7 on 2023-04-06 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=160)),
                ('price', models.FloatField(default=0)),
                ('cover_photo', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
    ]
