# Generated by Django 4.1.7 on 2023-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cover_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
